spring.application.name=couriertracking

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always

server.port=8080

#trigger to see the stack trace. off by default
app.debug=false

store.initialize.filePath=store.json
courier.initialize.filePath=courier.json
error.messages.path=classpath:i18n/messages
logging.level.org.apache.tomcat.util.net.NioEndpoint=INFO