swagger.contact.email=f.yesilyurt@outlook.com
swagger.contact.name=Furkan Yesilyurt
swagger.info.title=Courier Tracking API
swagger.info.description=Courier Tracking System | This API is developed for Migros One Study Case.
swagger.info.version=1.0.0